### ISSUE TITLE
教程真的是一言难尽，创建api时生成的配置放哪？

### ISSUE THREAD

**Issue by 3377** [Yohann0617/oci-helper#1]

**Comment by Yohann0617** [comment]
.pem文件放在/app/oci-helper/keys目录下，然后就可以启动服务了，在文本端添加配置，记得最后一项key_path=你们密钥文件.pem

**Comment by 3377** [comment]
我实际测了下，基于docker-compose，可以显示主区域的服务器，原来这个文件在web端配置。但是我拓展区的服务器如何显示呢~我切换后台为新增区域，新增API，配置还是主区域的

**Comment by Yohann0617** [comment]
> 我实际测了下，基于docker-compose，可以显示主区域的服务器，原来这个文件在web端配置。但是我拓展区的服务器如何显示呢~我切换后台为新增区域，新增API，配置还是主区域的

多区号的话，再新增一个配置，其他配置都一样，主要修改项：`region`

**Comment by 3377** [comment]
实测可用，目前可以换IP。有个BUG，新增成功后，我无法再编辑配置了。

**Comment by Yohann0617** [comment]
> 实测可用，目前可以换IP。有个BUG，新增成功后，我无法再编辑配置了。 另外希望新增功能，比如探长的那些。

可以删了重建哈哈哈，我没空开发，基本都是开发的核心功能

**Comment by Yohann0617** [comment]
> 可能我没法找到当时的配置文件在哪了。。。建议新增个编辑配置的功能，有空的话。有机不需要抢，现在没法测枪机。

这个配置文件，除非你控制台删除了，不然是不可能变的，所以不需要编辑。而且，我觉得还是不要提供查询配置项的接口好一点，容易泄露信息。
